### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by JKamsker** [reliable-webhook/webhooks#3]
The editor is blank when opening the extension throught the command pallete.
![image](https://user-images.githubusercontent.com/11245306/199125754-9ddc6e41-f49f-43c2-8034-20bd01b13518.png)
![image](https://user-images.githubusercontent.com/11245306/199125771-6bc74098-4cf0-4602-8d6a-c8b6feace30f.png)

**Comment by webhooksdev** [comment]
@JKamsker it was probably caused by a server error - everything should work correctly now.
